kind: pipeline
type: docker
name: default
steps:
  - name: Build & Pack
    image: node:14-alpine
    commands:
    - cd ./@frontend
    - npm install
    - npm run build
    - cd ..
    - tar -czf release.tar.gz ./@frontend/dist ./@backend 
  - name: Secure Transfer
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: vps_host
      user: 
        from_secret: vps_username
      key:
        from_secret: vps_private_key
      port: 22
      command_timeout: 2m
      target: /opt/web
      source: 
        - release.tar.gz
  - name: Remotly restart service
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: vps_host
      user: 
        from_secret: vps_username
      key:
        from_secret: vps_private_key
      port: 22
      command_timeout: 2m
      script:
        - cd /opt/web
        - tar -zcvf ./release.tar.gz . 
        - docker-compose down
        - rm -rf frontend
        - rm -rf backend
        - mv dist frontend
        - mv @backend backend
        - docker-compose up -d
