kind: pipeline
type: docker
name: default
steps:
  - name: Frontend Build Test
    image: node:14-alpine
    commands:
    - cd ./@frontend
    - npm install
    - npm run build
  - name: Backend Build Test
    image: node:14-alpine
    commands:
    - cd ./@backend
    - npm install
    - node ./src
