kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
steps:
  - name: Environment testing
    image: alpine
    commands:
    - pwd
    - ls -alh
  - name: Frontend Build Test
    image: node:17-alpine
    commands:
    - cd /@frontend
    - npm install
    - npm run build
  - name: Backend Build Test
    image: node:17-alpine
    commands:
    - cd /@backend
    - npm install
    - node /src/index.js