kind: pipeline
type: docker
name: default
steps:
  - name: Frontend Build
    image: node:14-alpine
    commands:
    - cd ./@frontend
    - npm install
    - npm run build
  - name: Secure Transfer
    image: appleboy/drone-scp
    settings:
      host:
      user:
      port: 22
      command_timeout: 1m
      target: /opt/web
      source: 
      - ./@frontend/dist
      - ./@backend
- name: Remotly restart service
    image: appleboy/drone-acp
    settings:
      host:
      user:
      port: 22
      command_timeout: 2m
      script:
        - docker-compose down
        - rm -rf frontend
        - rm -rf backend
        - mv dist frontend
        - mv @backend backend
        - docker-compose up -d
