kind: pipeline
type: docker
name: default
steps:
  - name: Build & Pack
    image: node:14-alpine
    commands:
    - cd ./@frontend
    - npm install
    - npm run build
  - name: Secure Transfer
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: vps_host
      user: 
        from_secret: vps_username
      key:
        from_secret: vps_private_key
      port: 22
      command_timeout: 2m
      target: /home/maintainer/web
      source:
        - ./@frontend/dist
        - ./@backend
  - name: Remotly restart service
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: vps_host
      user: 
        from_secret: vps_username
      key:
        from_secret: vps_private_key
      port: 22
      command_timeout: 2m
      script:
        - sudo su
        - cd /opt/web
        - cp /home/maintainer/web/* .
        - docker-compose down
        - rm -rf frontend
        - rm -rf backend
        - cp @frontend/dist frontend
        - cp @backend backend
        - rm -rf @frontend
        - rm -rf @backend
        - docker-compose up -d
