kind: pipeline
type: docker
name: default
steps:
  - name: Build & Pack
    image: node:14-alpine
    commands:
    - cd ./@frontend
    - npm install
    - npm run build
  - name: Secure Transfer
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: vps_host
      user: 
        from_secret: vps_username
      key:
        from_secret: vps_private_key
      port: 22
      command_timeout: 2m
      target: /home/maintainer/web
      source:
        - ./@frontend/dist
        - ./@backend
